export const metadat = {
    title : 'Next.js',
    description : 'Generated by Next Js'
}


export default function RootLayout({
    children,
}:{
    children:React.ReactNode
}){
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}